# Generated by Django 5.0 on 2023-12-09 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('address', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('aadhar_number', models.CharField(max_length=100)),
                ('cast', models.CharField(max_length=20)),
                ('emergency_contact', models.CharField(max_length=20)),
                ('hostel_room_number', models.CharField(max_length=10)),
                ('blood_group', models.CharField(max_length=10)),
                ('allergies', models.JSONField(default=list)),
                ('fees_payment_details', models.JSONField(default=list)),
            ],
        ),
    ]
