# Generated by Django 5.0 on 2023-12-23 08:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="students",
            name="hostel_room_number",
            field=models.CharField(max_length=10),
        ),
    ]
