# Generated by Django 5.0 on 2023-12-23 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0002_alter_students_hostel_room_number"),
        ("rooms", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="students",
            name="hostel_room_number",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="rooms.room",
            ),
        ),
    ]
