# Generated by Django 5.0 on 2023-12-20 14:35

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("room_number", models.IntegerField()),
                ("capacity", models.IntegerField()),
                ("rent", models.IntegerField()),
                ("facilities", models.JSONField(default=list)),
                ("number_of_study_tables", models.IntegerField()),
            ],
        ),
    ]
