# Generated by Django 5.0 on 2023-12-20 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bill_type", models.CharField(max_length=50)),
                ("amount", models.FloatField()),
                ("invoice_number", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Salary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("worker_type", models.CharField(max_length=50)),
                ("amount", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("amount_paid", models.FloatField()),
                ("notes", models.TextField(blank=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("tuition", "Tuition Fees"),
                            ("accommodation", "Accommodation Fees"),
                            ("salary", "Worker Salary"),
                            ("utility", "Utility Bill"),
                        ],
                        max_length=50,
                    ),
                ),
                ("hours_worked", models.IntegerField(blank=True, null=True)),
                ("overtime_hours", models.IntegerField(blank=True, null=True)),
                ("allowances", models.FloatField(blank=True, null=True)),
                (
                    "bill",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="payments.bill",
                    ),
                ),
                (
                    "cleaner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profiles.cleaners",
                    ),
                ),
                (
                    "cook",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profiles.cooks",
                    ),
                ),
                (
                    "guard",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profiles.guards",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profiles.students",
                    ),
                ),
                (
                    "salary",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="payments.salary",
                    ),
                ),
            ],
        ),
    ]
