# Generated by Django 5.0 on 2023-12-26 14:21

import datetime
import payments.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bill",
            name="invoice_number",
        ),
        migrations.AddField(
            model_name="bill",
            name="bill_date",
            field=models.DateField(
                default=datetime.datetime(
                    2023, 12, 26, 14, 21, 26, 763091, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AddField(
            model_name="bill",
            name="due_date",
            field=models.DateField(default=payments.models.default_due_date),
        ),
        migrations.AddField(
            model_name="bill",
            name="items",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="bill",
            name="payment_status",
            field=models.CharField(
                choices=[("pending", "Pending"), ("paid", "Paid")],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="bill",
            name="bill_type",
            field=models.CharField(
                choices=[
                    ("electricity", "Electricity"),
                    ("water", "Water"),
                    ("groceries", "groceries"),
                    ("other", "Other"),
                ],
                max_length=50,
            ),
        ),
    ]
