# Generated by Django 5.0 on 2023-12-28 13:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0002_remove_bill_invoice_number_bill_bill_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bill",
            name="bill_date",
            field=models.DateField(
                default=datetime.datetime(
                    2023, 12, 28, 13, 26, 1, 420185, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.DeleteModel(
            name="Payment",
        ),
        migrations.DeleteModel(
            name="Salary",
        ),
    ]
