# Generated by Django 5.0 on 2024-01-10 09:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Inventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item_name", models.CharField(max_length=100)),
                ("category", models.CharField(max_length=20)),
                ("quantity", models.IntegerField()),
                ("unit", models.CharField(max_length=20)),
                ("purchase_price", models.FloatField()),
                (
                    "purchase_date",
                    models.DateField(
                        default=datetime.datetime(
                            2024, 1, 10, 9, 8, 25, 895267, tzinfo=datetime.timezone.utc
                        )
                    ),
                ),
                ("vendor_name", models.CharField(max_length=100)),
                ("vendor_phone_number", models.CharField(max_length=15)),
                ("minimum_stock", models.IntegerField()),
                ("status", models.CharField(max_length=50)),
                ("notes", models.TextField(blank=True)),
            ],
        ),
    ]
